version: '3.4'

services:
  react-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app
