name: CI pipeline

on:
  push:
    branches:
      - main
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image
        run: |
          docker build -t react-app .

      - name: Save Docker image as tar
        run: |
          docker save react-app | gzip > react-app.tar.gz

      - name: Upload Docker image
        uses: actions/upload-artifact@v3
        with:
          name: react-app-image
          path: react-app.tar.gz

  lint:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Docker image
        uses: actions/download-artifact@v3
        with:
          name: react-app-image
          path: ./

      - name: Load Docker image
        run: |
          gunzip -c react-app.tar.gz | docker load

      - name: Run Linting
        run: |
          docker run --rm react-app npm run lint
