name: CI pipeline

on:
  push:
    branches:
      - main
      - test

jobs:
  build:
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository_owner }}/react-app:${{ github.sha }} \
            --tag ghcr.io/${{ github.repository_owner }}/react-app:latest \
            --push .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image from GHCR
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/react-app:${{ github.sha }}

      - name: Run Testing
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/react-app:${{ github.sha }} npm run test:unit

  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker image from GHCR
        run: |
          docker pull ghcr.io/${{ github.repository_owner }}/react-app:${{ github.sha }}

      - name: Run Linting
        run: |
          docker run --rm ghcr.io/${{ github.repository_owner }}/react-app:${{ github.sha }} npm run lint
